name: CoderCo Combined

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: install dependencies
      run: |
        cd chapter4
        python -m pip install --upgrade pip

    - name: run tests
      run: |
        cd chapter4
        python -m unittest discover 

    - name: notify us of success
      run: echo "Test passed on python"
      if: success()

    