name: CoderCo Assignment 1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: build and push image
        run: |
          cd ..
          docker build -t siada2/project:v1 .
          docker push siada2/project:v1
      
      - name: testing workflow
        run: echo "succesfull"
        if: success()
    
      
    


     
    
    