name: CoderCo Assignment 1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: run image
        run: |
          docker pull siada2/project:v1
          docker run -p 4000:4000 siada2/project:v1
    
    
      
    


     
    
    