name: CoderCo Assignment 1

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v2

    - name: pull docker image
      run: |
        docker pull siada2/test:v1
      
      if: success()

     
    
    