name: CoderCo Assignment 1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.MY_SECRET }}

    
      - name: build and push image
        run: |
          docker build -t siada2/project:v1 .
          docker push siada2/project:v1
      
      - name: testing workflow
        run: echo "succesfull"
        if: success()
    
      
    


     
    
    